### ISSUE TITLE
sizecmp(), blockcmp() 코드 작성

### ISSUE THREAD

**Issue by can13any** [swengineering-team8/Project2#10]
//두 개의 파일 크기를 비교하는 함수 작성
void sizecmp(){
    printf("size compare\n");
    if((int)stat1.st_size > (int)stat2.st_size){
        printf("text1 is bigger\n"); 
    }
    else if((int)stat1.st_size < (int)stat2.st_size){
        printf("text2 is bigger\n"); 
    }
    else{
        printf("sizes are equal\n");         
    }
    printf("\n");
}

//두 개의 파일 블락 수를 비교하는 함수 작성
void blockcmp(){
    printf("block compare\n");
    if((int)stat1.st_blocks > (int)stat2.st_blocks){
        printf("text1 is bigger\n");
    }
    else if((int)stat1.st_blocks < (int)stat2.st_blocks){
        printf("text2 is bigger\n");
    }
    else{
        printf("sizes are equal\n"); 
    }
    printf("\n");
}

**Comment by Tung-Pham-Dev** [comment]
확인했습니다

**Comment by hun-0k** [comment]
확인했습니다.

**Comment by dev2sang** [comment]
수고하셨어요
