### ISSUE TITLE
About 'stat' structure and sys/stat.h header

### ISSUE THREAD

**Issue by dev2sang** [swengineering-team8/Project2#13]
https://man7.org/linux/man-pages/man0/sys_stat.h.0p.html
https://man7.org/linux/man-pages/man2/lstat.2.html

The Linux man-pages above will make our assignments easier.

**Comment by can13any** [comment]
참고하겠습니다!

**Comment by hun-0k** [comment]
읽어보겠습니다.

**Comment by Tung-Pham-Dev** [comment]
참고하겠습니다!

**Comment by dev2sang** [comment]
감사합니다!
