### ISSUE TITLE
The function localtime() refers to the same address in all attempts.

### ISSUE THREAD

**Issue by dev2sang** [swengineering-team8/Project2#14]
![image](https://user-images.githubusercontent.com/74052457/167836214-57f882ef-7f5c-48fa-b668-c22034b682a1.png)

Initializing tm structure type point with localhost() make time1 and time2 to point same address.

So, I changed the 'struct tm *' global variable pointer type into 'struct tm' general type.

Previous:
```
struct tm *time1, *time2;
```

change into:
```
struct tm time1, time2;
```

**Comment by can13any** [comment]
https://www.ibm.com/docs/ko/i/7.3?topic=functions-localtime-convert-time

![image](https://user-images.githubusercontent.com/97014341/167850531-15376499-9de5-4332-b332-b6d31bcefef1.png)

네 위 사이트도 읽어보니 localtime() 함수가 정적으로 할당된 버퍼를 사용해서 struct tm * 포인터에 중복된 값이 들어간다는 것으로 이해했습니다.
그래서 struct tm을 포인터가 아닌 구조체 변수로 바꾸었다는 것 확인했습니다.

**Comment by Tung-Pham-Dev** [comment]
확인했습니다.

**Comment by hun-0k** [comment]
확인했습니다.
