### ISSUE TITLE
filestat1 및 filestat2 코드 작성

### ISSUE THREAD

**Issue by Tung-Pham-Dev** [swengineering-team8/Project2#2]
> //파일 1의 정보를 가져오는 함수 작성

void filestat1(){
	char path[] = "text1";
	int res = stat(path,&stat1);
	if(res == -1)
		printf("Erorr: %s exists.\n", path);
}

> //파일 2의 정보를 가져오는 함수 작성

void filestat2(){
	char path[] = "text2";
	int res = stat(path,&stat1);
	if(res == -1)
		printf("Erorr: %s exists.\n", path);
}

===============================
저는 위처럼 함수를 작성하려고 하는데 혹시 틀린 부분이 있으면 말씀해 주세요. 제가 바로 수정하겠습니다.

**Comment by Tung-Pham-Dev** [comment]
> //파일 1의 정보를 가져오는 함수 작성

void filestat1(){
    	char path[] = "text1";
	int res = stat(path,&stat1);
	if(res == -1)
		printf("Erorr: %s exists.\n", path);

}

> //파일` 2의 정보를 가져오는 함수 작성

void filestat2(){
    	char path[] = "text2";
	int res = stat(path,&stat1);
	if(res == -1)
		printf("Erorr: %s exists.\n", path);

}
=================================
이런 것으로 수정했습니다.

**Comment by dev2sang** [comment]
확인했습니다.  👍👍👍

**Comment by can13any** [comment]
확인했습니다!

**Comment by hun-0k** [comment]
확인했습니다.
