### ISSUE TITLE
filestat1 및 filestat2 코드 리뷰

### ISSUE THREAD

**Issue by Tung-Pham-Dev** [swengineering-team8/Project2#4]
please check the function i wrote

**Comment by dev2sang** [comment]
I confirmed your code.
If other team members check and leave a comment,
you should close this issue.
And then, I will merge your pull request.

**Comment by Tung-Pham-Dev** [comment]
Yes. Thank you

**Comment by can13any** [comment]
확인했습니다 수고하셨습니다.

**Comment by hun-0k** [comment]
수고하셨습니다.
