### ISSUE TITLE
filetime1, filetime2 코드 작성

### ISSUE THREAD

**Issue by hun-0k** [swengineering-team8/Project2#7]
//파일 1의 시간 정보를 가져오는 함수 작성
void filetime1(){
     	time1=localtime(&stat1.st_mtime); 
        printf("%04d-%02d-%02d %02d:%02d\n", 
                time1->tm_year+1900, time1->tm_mon+1, 
                time1->tm_mday, time1->tm_hour, 
                time1->tm_min);   
}

//파일 2의 시간 정보를 가져오는 함수 작성
void filetime2(){
            time2=localtime(&stat2.st_mtime); 
        printf("%04d-%02d-%02d %02d:%02d\n", 
                time2->tm_year+1900, time2->tm_mon+1, 
                time2->tm_mday, time2->tm_hour, 
                time2->tm_min);
}

**Comment by Tung-Pham-Dev** [comment]
확인했습니다.

**Comment by can13any** [comment]
확인했습니다.

**Comment by dev2sang** [comment]
출력까지 해주셨네요! 수고하셨습니다.
