### ISSUE TITLE
sizecmp(), blockcmp() 기반 기술조사

### ISSUE THREAD

**Issue by can13any** [swengineering-team8/Project2#9]
struct stat의 st_size, st_blocks 변수를 사용하여 파일의 크기와 block의 크기를 비교합니다.

https://www.it-note.kr/173
https://bodamnury.tistory.com/38
위와 같은 사이트에서 참고했습니다.

**Comment by Tung-Pham-Dev** [comment]
참고하겠습니다.

**Comment by hun-0k** [comment]
읽어보겠습니다.

**Comment by dev2sang** [comment]
👍
